[theme]
# Primary accent color for interactive elements.
primaryColor = "#ffcc00"

# Background color for the main content area.
backgroundColor = "#1a1a2e"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2a2a3a"

# Color used for almost all text.
textColor = "#e0e0e0"